version: "3.3"

services:
  redis:
  
    build: tests/
    
    volumes:
      - ./volumes/redis:/data
    
    ports: 
      - 6379:6379


  qr_validator:
  
    build: qrValidator/

    links:
      - redis

    depends_on:
      - redis